### PR TITLE
Rebuild

### PR DESCRIPTION
**Pull request by gillins**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] [Re-rendered]( https://conda-forge.org/docs/conda_smithy.html#how-to-re-render ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
@petebunting @danclewley any idea what this error means? Seems to be in the boost python bindings...

**Comment by petebunting** [comment]
Thanks for looking at this @gillins, really appreciated. 

I've just had a quick look (travelling at the moment) and I can't see anything which looks obvious. I assume the SPDLib module compiles OK without the boost-python spdpy module? If it does then maybe leave this out for the moment, I'll try to have more of a look over the next few weeks and see if I can fix. Unless @danclewley has any ideas?

As far as I am aware, the spdpy isn't used very much. One of my PhD students has used it to import data as just a slight adaptation to something which was done a while ago but people are best using pylidar if it is new code. The reason people are still using SPDLib is the command line tools as far as I am aware so these haven't been replicated in pylidar.

**Comment by danclewley** [comment]
If it compiles without `spdpy` I'd say go with that. We were building without spdpy before but had some emails asking about it, this was a while ago now though so not sure if it is still being used now.

**Comment by gillins** [comment]
@conda-forge-admin, please rerender

**Comment by gillins** [comment]
OK I've skipped the Python bindings which makes it much quicker to build - don't have to do a build for each Python version. If someone really needs them then hopefully they can also provide a patch to fix this error :smile:

**Comment by petebunting** [comment]
Thanks Sam. 

I’ve created docker container and singularity image:

https://cloud.docker.com/repository/docker/petebunting/spdlib <https://cloud.docker.com/repository/docker/petebunting/spdlib>
https://www.singularity-hub.org/collections/2651 <https://www.singularity-hub.org/collections/2651>

docker image seems to be working OK.

Cheers, Pete

**Pull request merged**
